<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Package.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>$(Product) Grasshopper</AssemblyTitle>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Extensions\Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Embed\**\*" />
    <None Include="$(RootDir)build\icon.png" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>

  <Target Name="Rename" AfterTargets="AfterBuild" Condition="'$(ContinuePackingAfterGeneratingNuspec)' != 'true'">
    <Move SourceFiles="$(TargetPath)" DestinationFiles="$(TargetDir)$(Product).gha" />
  </Target>
</Project>
