<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Package.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>Extensions Core</AssemblyTitle>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="8.21.25188.17001" ExcludeAssets="runtime" />
    <PackageReference Include="Robots.Rhino" Version="2.1.0" ExcludeAssets="runtime" />
    <PackageReference Include="morelinq" Version="4.4.0" />
    <PackageReference Include="geometry3Sharp" Version="1.0.324" />
    <PackageReference Include="Clipper2" Version="2.0.0" />
    <PackageReference Include="SkeletonNet" Version="1.0.0" />

    <Reference Include="gsGCode" HintPath="..\..\lib\gsGCode.dll" />
  </ItemGroup>

</Project>
